name: m3u-hn update

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download M3U file
      run: |
        curl -o temp-ipv6.m3u https://fastly.jsdelivr.net/gh/fanmingming/live/tv/m3u/ipv6.m3u

    - name: Append content from append.m3u
      run: |
        cat append.m3u >> temp-ipv6.m3u

    - name: Move updated file to ipv6-hn.m3u
      run: |
        mv temp-ipv6.m3u ipv6-hn.m3u

    - name: Commit and push changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "your-username"
        git add ipv6-hn.m3u
        git commit -m "Daily update of ipv6-hn.m3u"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
